-- Import NetUp users from add_user.txt and tournament registration CSV.
-- Generated by Codex on 2026-06-30.
-- Total unique users in this import: 138.
-- No synthetic tournament+ emails are created. CSV rows use only their real representative email.
-- This SQL is idempotent and also removes old synthetic tournament+ users when they are unreferenced.

BEGIN;

CREATE TEMP TABLE tmp_netup_user_import (
  email text PRIMARY KEY,
  full_name text NOT NULL,
  phone text,
  avatar_url text NOT NULL,
  created_at timestamptz NOT NULL,
  source text NOT NULL,
  student_code text
) ON COMMIT DROP;

INSERT INTO tmp_netup_user_import (
  email,
  full_name,
  phone,
  avatar_url,
  created_at,
  source,
  student_code
)
VALUES
  ('kientthe180644@fpt.edu.vn', 'Trần Trung Kiên', NULL, 'https://ui-avatars.com/api/?name=Tr%E1%BA%A7n+Trung+Ki%C3%AAn&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BA%A7n+Trung+Ki%C3%AAn+kientthe180644%40fpt.edu.vn', '2026-06-19 23:22:01+07', 'add_user.txt', 'HE180644'),
  ('quynhntha180024@fpt.edu.vn', 'Nguyễn Thị Quỳnh', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Th%E1%BB%8B+Qu%E1%BB%B3nh&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Th%E1%BB%8B+Qu%E1%BB%B3nh+quynhntha180024%40fpt.edu.vn', '2026-05-15 10:45:18+07', 'add_user.txt', 'HA180024'),
  ('lannthha180045@fpt.edu.vn', 'Nguyễn Thị Hương Lan', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Th%E1%BB%8B+H%C6%B0%C6%A1ng+Lan&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Th%E1%BB%8B+H%C6%B0%C6%A1ng+Lan+lannthha180045%40fpt.edu.vn', '2026-05-21 21:10:28+07', 'add_user.txt', 'HA180045'),
  ('ngannttha194048@fpt.edu.vn', 'Nguyễn Thị Thảo Ngân', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Th%E1%BB%8B+Th%E1%BA%A3o+Ng%C3%A2n&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Th%E1%BB%8B+Th%E1%BA%A3o+Ng%C3%A2n+ngannttha194048%40fpt.edu.vn', '2026-06-02 19:38:18+07', 'add_user.txt', 'HA194048'),
  ('manhvhhe151064@fpt.edu.vn', 'Vũ Hữu Mạnh', NULL, 'https://ui-avatars.com/api/?name=V%C5%A9+H%E1%BB%AFu+M%E1%BA%A1nh&background=random&color=fff&size=96&bold=true&format=png&seed=V%C5%A9+H%E1%BB%AFu+M%E1%BA%A1nh+manhvhhe151064%40fpt.edu.vn', '2026-06-23 05:50:01+07', 'add_user.txt', 'HE151064'),
  ('namldhe163161@fpt.edu.vn', 'Lê Duy Nam', NULL, 'https://ui-avatars.com/api/?name=L%C3%AA+Duy+Nam&background=random&color=fff&size=96&bold=true&format=png&seed=L%C3%AA+Duy+Nam+namldhe163161%40fpt.edu.vn', '2026-05-30 10:14:46+07', 'add_user.txt', 'HE163161'),
  ('minhnnhe171269@fpt.edu.vn', 'Nguyễn Nhật Minh', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Nh%E1%BA%ADt+Minh&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Nh%E1%BA%ADt+Minh+minhnnhe171269%40fpt.edu.vn', '2026-06-08 18:28:18+07', 'add_user.txt', 'HE171269'),
  ('vanntthe172704@fpt.edu.vn', 'Nguyễn Thị Thảo Vân', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Th%E1%BB%8B+Th%E1%BA%A3o+V%C3%A2n&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Th%E1%BB%8B+Th%E1%BA%A3o+V%C3%A2n+vanntthe172704%40fpt.edu.vn', '2026-06-07 09:53:01+07', 'add_user.txt', 'HE172704'),
  ('quanlnmhe173240@fpt.edu.vn', 'Lê Nam Minh Quân', NULL, 'https://ui-avatars.com/api/?name=L%C3%AA+Nam+Minh+Qu%C3%A2n&background=random&color=fff&size=96&bold=true&format=png&seed=L%C3%AA+Nam+Minh+Qu%C3%A2n+quanlnmhe173240%40fpt.edu.vn', '2026-05-23 19:16:24+07', 'add_user.txt', 'HE173240'),
  ('dieunhhe173250@fpt.edu.vn', 'Nguyễn Huyền Diệu', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Huy%E1%BB%81n+Di%E1%BB%87u&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Huy%E1%BB%81n+Di%E1%BB%87u+dieunhhe173250%40fpt.edu.vn', '2026-06-12 08:06:01+07', 'add_user.txt', 'HE173250'),
  ('longnvhe176277@fpt.edu.vn', 'Nguyễn Văn Long', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+V%C4%83n+Long&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+V%C4%83n+Long+longnvhe176277%40fpt.edu.vn', '2026-06-19 13:47:38+07', 'add_user.txt', 'HE176277'),
  ('thangnhhe176506@fpt.edu.vn', 'Nguyễn Hữu Thắng', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+H%E1%BB%AFu+Th%E1%BA%AFng&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+H%E1%BB%AFu+Th%E1%BA%AFng+thangnhhe176506%40fpt.edu.vn', '2026-06-20 09:52:07+07', 'add_user.txt', 'HE176506'),
  ('minhlqhe176560@fpt.edu.vn', 'Lê Quang Minh', NULL, 'https://ui-avatars.com/api/?name=L%C3%AA+Quang+Minh&background=random&color=fff&size=96&bold=true&format=png&seed=L%C3%AA+Quang+Minh+minhlqhe176560%40fpt.edu.vn', '2026-06-08 17:10:11+07', 'add_user.txt', 'HE176560'),
  ('anhdhlhe180028@fpt.edu.vn', 'Đặng Huyền Linh Anh', NULL, 'https://ui-avatars.com/api/?name=%C4%90%E1%BA%B7ng+Huy%E1%BB%81n+Linh+Anh&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90%E1%BA%B7ng+Huy%E1%BB%81n+Linh+Anh+anhdhlhe180028%40fpt.edu.vn', '2026-05-22 12:46:12+07', 'add_user.txt', 'HE180028'),
  ('minhlahe180101@fpt.edu.vn', 'Lương Anh Minh', NULL, 'https://ui-avatars.com/api/?name=L%C6%B0%C6%A1ng+Anh+Minh&background=random&color=fff&size=96&bold=true&format=png&seed=L%C6%B0%C6%A1ng+Anh+Minh+minhlahe180101%40fpt.edu.vn', '2026-06-02 16:57:32+07', 'add_user.txt', 'HE180101'),
  ('hungnqhe180166@fpt.edu.vn', 'Nguyễn Quang Hùng', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Quang+H%C3%B9ng&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Quang+H%C3%B9ng+hungnqhe180166%40fpt.edu.vn', '2026-06-09 17:42:25+07', 'add_user.txt', 'HE180166'),
  ('ducnvhe180297@fpt.edu.vn', 'Ngô Văn Đức', NULL, 'https://ui-avatars.com/api/?name=Ng%C3%B4+V%C4%83n+%C4%90%E1%BB%A9c&background=random&color=fff&size=96&bold=true&format=png&seed=Ng%C3%B4+V%C4%83n+%C4%90%E1%BB%A9c+ducnvhe180297%40fpt.edu.vn', '2026-05-15 09:27:22+07', 'add_user.txt', 'HE180297'),
  ('minhpvhe180323@fpt.edu.vn', 'Phạm Văn Minh', NULL, 'https://ui-avatars.com/api/?name=Ph%E1%BA%A1m+V%C4%83n+Minh&background=random&color=fff&size=96&bold=true&format=png&seed=Ph%E1%BA%A1m+V%C4%83n+Minh+minhpvhe180323%40fpt.edu.vn', '2026-05-22 06:10:05+07', 'add_user.txt', 'HE180323'),
  ('hoangtmhe180734@fpt.edu.vn', 'Trương Minh Hoàng', NULL, 'https://ui-avatars.com/api/?name=Tr%C6%B0%C6%A1ng+Minh+Ho%C3%A0ng&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%C6%B0%C6%A1ng+Minh+Ho%C3%A0ng+hoangtmhe180734%40fpt.edu.vn', '2026-06-19 15:50:30+07', 'add_user.txt', 'HE180734'),
  ('luonghdhe180950@fpt.edu.vn', 'Hoàng Đức Lương', NULL, 'https://ui-avatars.com/api/?name=Ho%C3%A0ng+%C4%90%E1%BB%A9c+L%C6%B0%C6%A1ng&background=random&color=fff&size=96&bold=true&format=png&seed=Ho%C3%A0ng+%C4%90%E1%BB%A9c+L%C6%B0%C6%A1ng+luonghdhe180950%40fpt.edu.vn', '2026-06-11 04:16:38+07', 'add_user.txt', 'HE180950'),
  ('khoitthe180953@fpt.edu.vn', 'Trần Trọng Khôi', NULL, 'https://ui-avatars.com/api/?name=Tr%E1%BA%A7n+Tr%E1%BB%8Dng+Kh%C3%B4i&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BA%A7n+Tr%E1%BB%8Dng+Kh%C3%B4i+khoitthe180953%40fpt.edu.vn', '2026-06-04 14:07:28+07', 'add_user.txt', 'HE180953'),
  ('namnthe180997@fpt.edu.vn', 'Nguyễn Thế Nam', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Th%E1%BA%BF+Nam&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Th%E1%BA%BF+Nam+namnthe180997%40fpt.edu.vn', '2026-06-05 05:56:48+07', 'add_user.txt', 'HE180997'),
  ('sondhthe181119@fpt.edu.vn', 'Dương Hữu Thái Sơn', NULL, 'https://ui-avatars.com/api/?name=D%C6%B0%C6%A1ng+H%E1%BB%AFu+Th%C3%A1i+S%C6%A1n&background=random&color=fff&size=96&bold=true&format=png&seed=D%C6%B0%C6%A1ng+H%E1%BB%AFu+Th%C3%A1i+S%C6%A1n+sondhthe181119%40fpt.edu.vn', '2026-06-12 15:15:15+07', 'add_user.txt', 'HE181119'),
  ('sonnphe181147@fpt.edu.vn', 'Nguyễn Phi Sơn', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Phi+S%C6%A1n&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Phi+S%C6%A1n+sonnphe181147%40fpt.edu.vn', '2026-05-29 15:29:06+07', 'add_user.txt', 'HE181147'),
  ('duynthe181173@fpt.edu.vn', 'Nguyễn Tiến Duy', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Ti%E1%BA%BFn+Duy&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Ti%E1%BA%BFn+Duy+duynthe181173%40fpt.edu.vn', '2026-06-15 08:50:48+07', 'add_user.txt', 'HE181173'),
  ('thanhndhe181562@fpt.edu.vn', 'Nguyễn Doanh Thành', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Doanh+Th%C3%A0nh&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Doanh+Th%C3%A0nh+thanhndhe181562%40fpt.edu.vn', '2026-05-15 12:05:53+07', 'add_user.txt', 'HE181562'),
  ('tungcthe181657@fpt.edu.vn', 'Chu Thanh Tùng', NULL, 'https://ui-avatars.com/api/?name=Chu+Thanh+T%C3%B9ng&background=random&color=fff&size=96&bold=true&format=png&seed=Chu+Thanh+T%C3%B9ng+tungcthe181657%40fpt.edu.vn', '2026-05-29 11:51:25+07', 'add_user.txt', 'HE181657'),
  ('thinhnphe181767@fpt.edu.vn', 'Nguyễn Phú Thịnh', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Ph%C3%BA+Th%E1%BB%8Bnh&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Ph%C3%BA+Th%E1%BB%8Bnh+thinhnphe181767%40fpt.edu.vn', '2026-06-07 07:25:38+07', 'add_user.txt', 'HE181767'),
  ('thanhnche181769@fpt.edu.vn', 'Nguyễn Công Thành', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+C%C3%B4ng+Th%C3%A0nh&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+C%C3%B4ng+Th%C3%A0nh+thanhnche181769%40fpt.edu.vn', '2026-06-02 20:46:24+07', 'add_user.txt', 'HE181769'),
  ('hieudthe182175@fpt.edu.vn', 'Đoàn Trung Hiếu', NULL, 'https://ui-avatars.com/api/?name=%C4%90o%C3%A0n+Trung+Hi%E1%BA%BFu&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90o%C3%A0n+Trung+Hi%E1%BA%BFu+hieudthe182175%40fpt.edu.vn', '2026-06-13 14:21:46+07', 'add_user.txt', 'HE182175'),
  ('dungdahe182194@fpt.edu.vn', 'Dương Anh Dũng', NULL, 'https://ui-avatars.com/api/?name=D%C6%B0%C6%A1ng+Anh+D%C5%A9ng&background=random&color=fff&size=96&bold=true&format=png&seed=D%C6%B0%C6%A1ng+Anh+D%C5%A9ng+dungdahe182194%40fpt.edu.vn', '2026-06-14 19:25:36+07', 'add_user.txt', 'HE182194'),
  ('tuyenpvhe182212@fpt.edu.vn', 'Phạm Văn Tuyền', NULL, 'https://ui-avatars.com/api/?name=Ph%E1%BA%A1m+V%C4%83n+Tuy%E1%BB%81n&background=random&color=fff&size=96&bold=true&format=png&seed=Ph%E1%BA%A1m+V%C4%83n+Tuy%E1%BB%81n+tuyenpvhe182212%40fpt.edu.vn', '2026-06-20 02:00:17+07', 'add_user.txt', 'HE182212'),
  ('haucvhe182292@fpt.edu.vn', 'Cao Văn Hậu', NULL, 'https://ui-avatars.com/api/?name=Cao+V%C4%83n+H%E1%BA%ADu&background=random&color=fff&size=96&bold=true&format=png&seed=Cao+V%C4%83n+H%E1%BA%ADu+haucvhe182292%40fpt.edu.vn', '2026-06-04 09:59:07+07', 'add_user.txt', 'HE182292'),
  ('anhdvthe186053@fpt.edu.vn', 'Đặng Văn Thái Anh', NULL, 'https://ui-avatars.com/api/?name=%C4%90%E1%BA%B7ng+V%C4%83n+Th%C3%A1i+Anh&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90%E1%BA%B7ng+V%C4%83n+Th%C3%A1i+Anh+anhdvthe186053%40fpt.edu.vn', '2026-06-22 07:39:01+07', 'add_user.txt', 'HE186053'),
  ('ducnhhe186325@fpt.edu.vn', 'Nông Hoàng Đức', NULL, 'https://ui-avatars.com/api/?name=N%C3%B4ng+Ho%C3%A0ng+%C4%90%E1%BB%A9c&background=random&color=fff&size=96&bold=true&format=png&seed=N%C3%B4ng+Ho%C3%A0ng+%C4%90%E1%BB%A9c+ducnhhe186325%40fpt.edu.vn', '2026-05-19 09:01:41+07', 'add_user.txt', 'HE186325'),
  ('hunghmhe186414@fpt.edu.vn', 'Hoàng Mạnh Hùng', NULL, 'https://ui-avatars.com/api/?name=Ho%C3%A0ng+M%E1%BA%A1nh+H%C3%B9ng&background=random&color=fff&size=96&bold=true&format=png&seed=Ho%C3%A0ng+M%E1%BA%A1nh+H%C3%B9ng+hunghmhe186414%40fpt.edu.vn', '2026-06-16 11:54:52+07', 'add_user.txt', 'HE186414'),
  ('huongntmhe186558@fpt.edu.vn', 'Nguyễn Thị Mai Hương', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Th%E1%BB%8B+Mai+H%C6%B0%C6%A1ng&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Th%E1%BB%8B+Mai+H%C6%B0%C6%A1ng+huongntmhe186558%40fpt.edu.vn', '2026-05-15 12:18:19+07', 'add_user.txt', 'HE186558'),
  ('anhnlhe186577@fpt.edu.vn', 'Nguyễn Lan Anh', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Lan+Anh&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Lan+Anh+anhnlhe186577%40fpt.edu.vn', '2026-05-25 07:32:06+07', 'add_user.txt', 'HE186577'),
  ('hieunhhe186643@fpt.edu.vn', 'Nguyễn Hoàng Hiếu', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Ho%C3%A0ng+Hi%E1%BA%BFu&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Ho%C3%A0ng+Hi%E1%BA%BFu+hieunhhe186643%40fpt.edu.vn', '2026-05-20 07:35:00+07', 'add_user.txt', 'HE186643'),
  ('thangnlqhe186665@fpt.edu.vn', 'Nguyễn Lê Quang Thắng', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+L%C3%AA+Quang+Th%E1%BA%AFng&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+L%C3%AA+Quang+Th%E1%BA%AFng+thangnlqhe186665%40fpt.edu.vn', '2026-06-21 02:32:45+07', 'add_user.txt', 'HE186665'),
  ('myntthe186699@fpt.edu.vn', 'Nguyễn Thị Trà My', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Th%E1%BB%8B+Tr%C3%A0+My&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Th%E1%BB%8B+Tr%C3%A0+My+myntthe186699%40fpt.edu.vn', '2026-06-17 10:57:12+07', 'add_user.txt', 'HE186699'),
  ('khanhddhe186712@fpt.edu.vn', 'Đới Duy Khánh', NULL, 'https://ui-avatars.com/api/?name=%C4%90%E1%BB%9Bi+Duy+Kh%C3%A1nh&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90%E1%BB%9Bi+Duy+Kh%C3%A1nh+khanhddhe186712%40fpt.edu.vn', '2026-06-12 19:25:26+07', 'add_user.txt', 'HE186712'),
  ('lucvdhe186800@fpt.edu.vn', 'Vũ Đức Lực', NULL, 'https://ui-avatars.com/api/?name=V%C5%A9+%C4%90%E1%BB%A9c+L%E1%BB%B1c&background=random&color=fff&size=96&bold=true&format=png&seed=V%C5%A9+%C4%90%E1%BB%A9c+L%E1%BB%B1c+lucvdhe186800%40fpt.edu.vn', '2026-06-06 16:21:06+07', 'add_user.txt', 'HE186800'),
  ('vinhnthe186877@fpt.edu.vn', 'Nguyễn Thế Vinh', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Th%E1%BA%BF+Vinh&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Th%E1%BA%BF+Vinh+vinhnthe186877%40fpt.edu.vn', '2026-06-11 16:18:59+07', 'add_user.txt', 'HE186877'),
  ('mihhhe186879@fpt.edu.vn', 'Hà Hoàng Mi', NULL, 'https://ui-avatars.com/api/?name=H%C3%A0+Ho%C3%A0ng+Mi&background=random&color=fff&size=96&bold=true&format=png&seed=H%C3%A0+Ho%C3%A0ng+Mi+mihhhe186879%40fpt.edu.vn', '2026-05-22 17:44:56+07', 'add_user.txt', 'HE186879'),
  ('thaolphe187244@fpt.edu.vn', 'Lê Phương Thảo', NULL, 'https://ui-avatars.com/api/?name=L%C3%AA+Ph%C6%B0%C6%A1ng+Th%E1%BA%A3o&background=random&color=fff&size=96&bold=true&format=png&seed=L%C3%AA+Ph%C6%B0%C6%A1ng+Th%E1%BA%A3o+thaolphe187244%40fpt.edu.vn', '2026-06-14 17:23:00+07', 'add_user.txt', 'HE187244'),
  ('anhntlhe187298@fpt.edu.vn', 'Nguyễn Trần Lan Anh', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Tr%E1%BA%A7n+Lan+Anh&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Tr%E1%BA%A7n+Lan+Anh+anhntlhe187298%40fpt.edu.vn', '2026-06-03 22:44:53+07', 'add_user.txt', 'HE187298'),
  ('duongnthe187318@fpt.edu.vn', 'Nguyễn Thanh Dương', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Thanh+D%C6%B0%C6%A1ng&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Thanh+D%C6%B0%C6%A1ng+duongnthe187318%40fpt.edu.vn', '2026-06-10 05:18:09+07', 'add_user.txt', 'HE187318'),
  ('longnthe187346@fpt.edu.vn', 'Ngô Trung Long', NULL, 'https://ui-avatars.com/api/?name=Ng%C3%B4+Trung+Long&background=random&color=fff&size=96&bold=true&format=png&seed=Ng%C3%B4+Trung+Long+longnthe187346%40fpt.edu.vn', '2026-06-16 16:03:17+07', 'add_user.txt', 'HE187346'),
  ('namtnnha189000@fpt.edu.vn', 'Trần Nguyễn Ngọc Nam', NULL, 'https://ui-avatars.com/api/?name=Tr%E1%BA%A7n+Nguy%E1%BB%85n+Ng%E1%BB%8Dc+Nam&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BA%A7n+Nguy%E1%BB%85n+Ng%E1%BB%8Dc+Nam+namtnnha189000%40fpt.edu.vn', '2026-06-06 05:44:44+07', 'add_user.txt', 'HA189000'),
  ('thaitqhe171880@fpt.edu.vn', 'Trần Quốc Thái', NULL, 'https://ui-avatars.com/api/?name=Tr%E1%BA%A7n+Qu%E1%BB%91c+Th%C3%A1i&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BA%A7n+Qu%E1%BB%91c+Th%C3%A1i+thaitqhe171880%40fpt.edu.vn', '2026-06-12 17:27:01+07', 'add_user.txt', 'HE171880'),
  ('sondnhe180400@fpt.edu.vn', 'Đinh Ngọc Sơn', NULL, 'https://ui-avatars.com/api/?name=%C4%90inh+Ng%E1%BB%8Dc+S%C6%A1n&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90inh+Ng%E1%BB%8Dc+S%C6%A1n+sondnhe180400%40fpt.edu.vn', '2026-06-04 17:32:03+07', 'add_user.txt', 'HE180400'),
  ('longnhhe181326@fpt.edu.vn', 'Nguyễn Hoàng Long', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Ho%C3%A0ng+Long&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Ho%C3%A0ng+Long+longnhhe181326%40fpt.edu.vn', '2026-05-18 14:44:05+07', 'add_user.txt', 'HE181326'),
  ('daidqhe181335@fpt.edu.vn', 'Đỗ Quang Đại', NULL, 'https://ui-avatars.com/api/?name=%C4%90%E1%BB%97+Quang+%C4%90%E1%BA%A1i&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90%E1%BB%97+Quang+%C4%90%E1%BA%A1i+daidqhe181335%40fpt.edu.vn', '2026-06-16 04:17:02+07', 'add_user.txt', 'HE181335'),
  ('datdthe181500@fpt.edu.vn', 'Đỗ Tiến Đạt', NULL, 'https://ui-avatars.com/api/?name=%C4%90%E1%BB%97+Ti%E1%BA%BFn+%C4%90%E1%BA%A1t&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90%E1%BB%97+Ti%E1%BA%BFn+%C4%90%E1%BA%A1t+datdthe181500%40fpt.edu.vn', '2026-06-11 18:44:34+07', 'add_user.txt', 'HE181500'),
  ('trongpdhe181640@fpt.edu.vn', 'Phạm Đức Trọng', NULL, 'https://ui-avatars.com/api/?name=Ph%E1%BA%A1m+%C4%90%E1%BB%A9c+Tr%E1%BB%8Dng&background=random&color=fff&size=96&bold=true&format=png&seed=Ph%E1%BA%A1m+%C4%90%E1%BB%A9c+Tr%E1%BB%8Dng+trongpdhe181640%40fpt.edu.vn', '2026-06-10 11:09:38+07', 'add_user.txt', 'HE181640'),
  ('vietnqhe181751@fpt.edu.vn', 'Nguyễn Quốc Việt', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Qu%E1%BB%91c+Vi%E1%BB%87t&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Qu%E1%BB%91c+Vi%E1%BB%87t+vietnqhe181751%40fpt.edu.vn', '2026-06-13 15:14:25+07', 'add_user.txt', 'HE181751'),
  ('haoqtthe181812@fpt.edu.vn', 'Quách Thị Thu Hảo', NULL, 'https://ui-avatars.com/api/?name=Qu%C3%A1ch+Th%E1%BB%8B+Thu+H%E1%BA%A3o&background=random&color=fff&size=96&bold=true&format=png&seed=Qu%C3%A1ch+Th%E1%BB%8B+Thu+H%E1%BA%A3o+haoqtthe181812%40fpt.edu.vn', '2026-06-11 18:19:23+07', 'add_user.txt', 'HE181812'),
  ('khangthe182024@fpt.edu.vn', 'Tạ Khang', NULL, 'https://ui-avatars.com/api/?name=T%E1%BA%A1+Khang&background=random&color=fff&size=96&bold=true&format=png&seed=T%E1%BA%A1+Khang+khangthe182024%40fpt.edu.vn', '2026-05-28 23:28:24+07', 'add_user.txt', 'HE182024'),
  ('datnnhe182327@fpt.edu.vn', 'Nguyễn Ngọc Đạt', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Ng%E1%BB%8Dc+%C4%90%E1%BA%A1t&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Ng%E1%BB%8Dc+%C4%90%E1%BA%A1t+datnnhe182327%40fpt.edu.vn', '2026-06-11 09:48:42+07', 'add_user.txt', 'HE182327'),
  ('canndhe182335@fpt.edu.vn', 'Nhữ Đình Cần', NULL, 'https://ui-avatars.com/api/?name=Nh%E1%BB%AF+%C4%90%C3%ACnh+C%E1%BA%A7n&background=random&color=fff&size=96&bold=true&format=png&seed=Nh%E1%BB%AF+%C4%90%C3%ACnh+C%E1%BA%A7n+canndhe182335%40fpt.edu.vn', '2026-06-14 08:04:14+07', 'add_user.txt', 'HE182335'),
  ('anhnphe186085@fpt.edu.vn', 'Nguyễn Phan Anh', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Phan+Anh&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Phan+Anh+anhnphe186085%40fpt.edu.vn', '2026-05-23 10:12:41+07', 'add_user.txt', 'HE186085'),
  ('khangndhe186523@fpt.edu.vn', 'Nguyễn Đăng Khang', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+%C4%90%C4%83ng+Khang&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+%C4%90%C4%83ng+Khang+khangndhe186523%40fpt.edu.vn', '2026-05-30 10:53:19+07', 'add_user.txt', 'HE186523'),
  ('namnxhe186666@fpt.edu.vn', 'Ngô Xuân Nam', NULL, 'https://ui-avatars.com/api/?name=Ng%C3%B4+Xu%C3%A2n+Nam&background=random&color=fff&size=96&bold=true&format=png&seed=Ng%C3%B4+Xu%C3%A2n+Nam+namnxhe186666%40fpt.edu.vn', '2026-06-12 21:53:24+07', 'add_user.txt', 'HE186666'),
  ('tammshe186670@fpt.edu.vn', 'Mai Sỹ Tâm', NULL, 'https://ui-avatars.com/api/?name=Mai+S%E1%BB%B9+T%C3%A2m&background=random&color=fff&size=96&bold=true&format=png&seed=Mai+S%E1%BB%B9+T%C3%A2m+tammshe186670%40fpt.edu.vn', '2026-06-05 04:44:06+07', 'add_user.txt', 'HE186670'),
  ('thangtxhe187306@fpt.edu.vn', 'Trịnh Xuân Thắng', NULL, 'https://ui-avatars.com/api/?name=Tr%E1%BB%8Bnh+Xu%C3%A2n+Th%E1%BA%AFng&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BB%8Bnh+Xu%C3%A2n+Th%E1%BA%AFng+thangtxhe187306%40fpt.edu.vn', '2026-06-23 03:29:50+07', 'add_user.txt', 'HE187306'),
  ('yendhhs180066@fpt.edu.vn', 'Đỗ Hải Yến', NULL, 'https://ui-avatars.com/api/?name=%C4%90%E1%BB%97+H%E1%BA%A3i+Y%E1%BA%BFn&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90%E1%BB%97+H%E1%BA%A3i+Y%E1%BA%BFn+yendhhs180066%40fpt.edu.vn', '2026-06-15 07:57:44+07', 'add_user.txt', 'HS180066'),
  ('chinths180312@fpt.edu.vn', 'Nguyễn Thuỳ Chi', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Thu%E1%BB%B3+Chi&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Thu%E1%BB%B3+Chi+chinths180312%40fpt.edu.vn', '2026-06-23 10:11:45+07', 'add_user.txt', 'HS180312'),
  ('thohdhs180426@fpt.edu.vn', 'Hoàng Đức Thọ', NULL, 'https://ui-avatars.com/api/?name=Ho%C3%A0ng+%C4%90%E1%BB%A9c+Th%E1%BB%8D&background=random&color=fff&size=96&bold=true&format=png&seed=Ho%C3%A0ng+%C4%90%E1%BB%A9c+Th%E1%BB%8D+thohdhs180426%40fpt.edu.vn', '2026-06-14 12:21:59+07', 'add_user.txt', 'HS180426'),
  ('nhitnhs180593@fpt.edu.vn', 'Trần Ngọc Nhi', NULL, 'https://ui-avatars.com/api/?name=Tr%E1%BA%A7n+Ng%E1%BB%8Dc+Nhi&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BA%A7n+Ng%E1%BB%8Dc+Nhi+nhitnhs180593%40fpt.edu.vn', '2026-05-27 16:28:13+07', 'add_user.txt', 'HS180593'),
  ('trangntths180642@fpt.edu.vn', 'Nguyễn Thị Thuỳ Trang', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Th%E1%BB%8B+Thu%E1%BB%B3+Trang&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Th%E1%BB%8B+Thu%E1%BB%B3+Trang+trangntths180642%40fpt.edu.vn', '2026-05-19 16:54:18+07', 'add_user.txt', 'HS180642'),
  ('linhptths186049@fpt.edu.vn', 'Phạm Thị Thùy Linh', NULL, 'https://ui-avatars.com/api/?name=Ph%E1%BA%A1m+Th%E1%BB%8B+Th%C3%B9y+Linh&background=random&color=fff&size=96&bold=true&format=png&seed=Ph%E1%BA%A1m+Th%E1%BB%8B+Th%C3%B9y+Linh+linhptths186049%40fpt.edu.vn', '2026-05-17 10:45:21+07', 'add_user.txt', 'HS186049'),
  ('lyntnhs186212@fpt.edu.vn', 'Nguyễn Thị Ngọc Ly', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Th%E1%BB%8B+Ng%E1%BB%8Dc+Ly&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Th%E1%BB%8B+Ng%E1%BB%8Dc+Ly+lyntnhs186212%40fpt.edu.vn', '2026-06-24 15:01:31+07', 'add_user.txt', 'HS186212'),
  ('hoangnmhs186432@fpt.edu.vn', 'Nguyễn Minh Hoàng', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Minh+Ho%C3%A0ng&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Minh+Ho%C3%A0ng+hoangnmhs186432%40fpt.edu.vn', '2026-05-20 12:49:50+07', 'add_user.txt', 'HS186432'),
  ('minhndhs186449@fpt.edu.vn', 'Nguyễn Đắc Minh', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+%C4%90%E1%BA%AFc+Minh&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+%C4%90%E1%BA%AFc+Minh+minhndhs186449%40fpt.edu.vn', '2026-05-20 22:38:41+07', 'add_user.txt', 'HS186449'),
  ('trangdths186456@fpt.edu.vn', 'Đỗ Thu Trang', NULL, 'https://ui-avatars.com/api/?name=%C4%90%E1%BB%97+Thu+Trang&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90%E1%BB%97+Thu+Trang+trangdths186456%40fpt.edu.vn', '2026-05-27 15:05:29+07', 'add_user.txt', 'HS186456'),
  ('quangnvhs186464@fpt.edu.vn', 'Nguyễn Văn Quang', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+V%C4%83n+Quang&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+V%C4%83n+Quang+quangnvhs186464%40fpt.edu.vn', '2026-05-16 14:22:30+07', 'add_user.txt', 'HS186464'),
  ('khanhtqhs189004@fpt.edu.vn', 'Trịnh Quốc Khánh', NULL, 'https://ui-avatars.com/api/?name=Tr%E1%BB%8Bnh+Qu%E1%BB%91c+Kh%C3%A1nh&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BB%8Bnh+Qu%E1%BB%91c+Kh%C3%A1nh+khanhtqhs189004%40fpt.edu.vn', '2026-06-10 05:37:36+07', 'add_user.txt', 'HS189004'),
  ('duclahe160057@fpt.edu.vn', 'Lưu Anh Đức', NULL, 'https://ui-avatars.com/api/?name=L%C6%B0u+Anh+%C4%90%E1%BB%A9c&background=random&color=fff&size=96&bold=true&format=png&seed=L%C6%B0u+Anh+%C4%90%E1%BB%A9c+duclahe160057%40fpt.edu.vn', '2026-05-28 23:50:47+07', 'add_user.txt', 'HE160057'),
  ('hieunthe176207@fpt.edu.vn', 'Nguyễn Trung Hiếu', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Trung+Hi%E1%BA%BFu&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Trung+Hi%E1%BA%BFu+hieunthe176207%40fpt.edu.vn', '2026-06-24 17:32:04+07', 'add_user.txt', 'HE176207'),
  ('annthe180486@fpt.edu.vn', 'Nguyễn Trường An', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Tr%C6%B0%E1%BB%9Dng+An&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Tr%C6%B0%E1%BB%9Dng+An+annthe180486%40fpt.edu.vn', '2026-06-07 01:58:09+07', 'add_user.txt', 'HE180486'),
  ('lamkdhe180931@fpt.edu.vn', 'Kiều Đức Lâm', NULL, 'https://ui-avatars.com/api/?name=Ki%E1%BB%81u+%C4%90%E1%BB%A9c+L%C3%A2m&background=random&color=fff&size=96&bold=true&format=png&seed=Ki%E1%BB%81u+%C4%90%E1%BB%A9c+L%C3%A2m+lamkdhe180931%40fpt.edu.vn', '2026-05-21 12:18:28+07', 'add_user.txt', 'HE180931'),
  ('khoapvhe181066@fpt.edu.vn', 'Phạm Văn Khoa', NULL, 'https://ui-avatars.com/api/?name=Ph%E1%BA%A1m+V%C4%83n+Khoa&background=random&color=fff&size=96&bold=true&format=png&seed=Ph%E1%BA%A1m+V%C4%83n+Khoa+khoapvhe181066%40fpt.edu.vn', '2026-05-26 17:22:58+07', 'add_user.txt', 'HE181066'),
  ('tuanpqhe181869@fpt.edu.vn', 'Phạm Quốc Tuấn', NULL, 'https://ui-avatars.com/api/?name=Ph%E1%BA%A1m+Qu%E1%BB%91c+Tu%E1%BA%A5n&background=random&color=fff&size=96&bold=true&format=png&seed=Ph%E1%BA%A1m+Qu%E1%BB%91c+Tu%E1%BA%A5n+tuanpqhe181869%40fpt.edu.vn', '2026-05-22 17:34:42+07', 'add_user.txt', 'HE181869'),
  ('duclmhe182150@fpt.edu.vn', 'Lê Minh Đức', NULL, 'https://ui-avatars.com/api/?name=L%C3%AA+Minh+%C4%90%E1%BB%A9c&background=random&color=fff&size=96&bold=true&format=png&seed=L%C3%AA+Minh+%C4%90%E1%BB%A9c+duclmhe182150%40fpt.edu.vn', '2026-05-21 22:54:04+07', 'add_user.txt', 'HE182150'),
  ('linhdpnhe182172@fpt.edu.vn', 'Đỗ Phạm Ngọc Linh', NULL, 'https://ui-avatars.com/api/?name=%C4%90%E1%BB%97+Ph%E1%BA%A1m+Ng%E1%BB%8Dc+Linh&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90%E1%BB%97+Ph%E1%BA%A1m+Ng%E1%BB%8Dc+Linh+linhdpnhe182172%40fpt.edu.vn', '2026-06-12 23:03:59+07', 'add_user.txt', 'HE182172'),
  ('phuongnmhe186354@fpt.edu.vn', 'Nguyễn Minh Phương', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Minh+Ph%C6%B0%C6%A1ng&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Minh+Ph%C6%B0%C6%A1ng+phuongnmhe186354%40fpt.edu.vn', '2026-06-06 00:14:54+07', 'add_user.txt', 'HE186354'),
  ('tanvmhe186791@fpt.edu.vn', 'Vũ Minh Tân', NULL, 'https://ui-avatars.com/api/?name=V%C5%A9+Minh+T%C3%A2n&background=random&color=fff&size=96&bold=true&format=png&seed=V%C5%A9+Minh+T%C3%A2n+tanvmhe186791%40fpt.edu.vn', '2026-05-15 23:46:46+07', 'add_user.txt', 'HE186791'),
  ('cuongndhe186815@fpt.edu.vn', 'Nguyễn Đức Cường', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+%C4%90%E1%BB%A9c+C%C6%B0%E1%BB%9Dng&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+%C4%90%E1%BB%A9c+C%C6%B0%E1%BB%9Dng+cuongndhe186815%40fpt.edu.vn', '2026-06-21 17:31:36+07', 'add_user.txt', 'HE186815'),
  ('dungtmhe186884@fpt.edu.vn', 'Trần Minh Dũng', NULL, 'https://ui-avatars.com/api/?name=Tr%E1%BA%A7n+Minh+D%C5%A9ng&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BA%A7n+Minh+D%C5%A9ng+dungtmhe186884%40fpt.edu.vn', '2026-05-28 22:41:13+07', 'add_user.txt', 'HE186884'),
  ('thangnche186902@fpt.edu.vn', 'Nguyễn Chiến Thắng', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Chi%E1%BA%BFn+Th%E1%BA%AFng&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Chi%E1%BA%BFn+Th%E1%BA%AFng+thangnche186902%40fpt.edu.vn', '2026-06-03 22:45:56+07', 'add_user.txt', 'HE186902'),
  ('khaidqhe186918@fpt.edu.vn', 'Đặng Quang Khải', NULL, 'https://ui-avatars.com/api/?name=%C4%90%E1%BA%B7ng+Quang+Kh%E1%BA%A3i&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90%E1%BA%B7ng+Quang+Kh%E1%BA%A3i+khaidqhe186918%40fpt.edu.vn', '2026-06-14 15:58:36+07', 'add_user.txt', 'HE186918'),
  ('trieulvhe187167@fpt.edu.vn', 'Lê Văn Triệu', NULL, 'https://ui-avatars.com/api/?name=L%C3%AA+V%C4%83n+Tri%E1%BB%87u&background=random&color=fff&size=96&bold=true&format=png&seed=L%C3%AA+V%C4%83n+Tri%E1%BB%87u+trieulvhe187167%40fpt.edu.vn', '2026-05-28 22:08:34+07', 'add_user.txt', 'HE187167'),
  ('hieulxhe187201@fpt.edu.vn', 'Lê Xuân Hiếu', NULL, 'https://ui-avatars.com/api/?name=L%C3%AA+Xu%C3%A2n+Hi%E1%BA%BFu&background=random&color=fff&size=96&bold=true&format=png&seed=L%C3%AA+Xu%C3%A2n+Hi%E1%BA%BFu+hieulxhe187201%40fpt.edu.vn', '2026-06-22 19:24:19+07', 'add_user.txt', 'HE187201'),
  ('trunglqhe170149@fpt.edu.vn', 'Lương Quang Trung', NULL, 'https://ui-avatars.com/api/?name=L%C6%B0%C6%A1ng+Quang+Trung&background=random&color=fff&size=96&bold=true&format=png&seed=L%C6%B0%C6%A1ng+Quang+Trung+trunglqhe170149%40fpt.edu.vn', '2026-06-23 07:56:00+07', 'add_user.txt', 'HE170149'),
  ('vietvdqhe170516@fpt.edu.vn', 'Vũ Đoàn Quốc Việt', NULL, 'https://ui-avatars.com/api/?name=V%C5%A9+%C4%90o%C3%A0n+Qu%E1%BB%91c+Vi%E1%BB%87t&background=random&color=fff&size=96&bold=true&format=png&seed=V%C5%A9+%C4%90o%C3%A0n+Qu%E1%BB%91c+Vi%E1%BB%87t+vietvdqhe170516%40fpt.edu.vn', '2026-05-26 08:13:50+07', 'add_user.txt', 'HE170516'),
  ('ngoctmhe171577@fpt.edu.vn', 'Trần Minh Ngọc', NULL, 'https://ui-avatars.com/api/?name=Tr%E1%BA%A7n+Minh+Ng%E1%BB%8Dc&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BA%A7n+Minh+Ng%E1%BB%8Dc+ngoctmhe171577%40fpt.edu.vn', '2026-05-24 17:09:27+07', 'add_user.txt', 'HE171577'),
  ('binhdthe176177@fpt.edu.vn', 'Đặng Tấn Bình', NULL, 'https://ui-avatars.com/api/?name=%C4%90%E1%BA%B7ng+T%E1%BA%A5n+B%C3%ACnh&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90%E1%BA%B7ng+T%E1%BA%A5n+B%C3%ACnh+binhdthe176177%40fpt.edu.vn', '2026-06-03 16:20:55+07', 'add_user.txt', 'HE176177'),
  ('anhbnhe180420@fpt.edu.vn', 'Bùi Ngọc Anh', NULL, 'https://ui-avatars.com/api/?name=B%C3%B9i+Ng%E1%BB%8Dc+Anh&background=random&color=fff&size=96&bold=true&format=png&seed=B%C3%B9i+Ng%E1%BB%8Dc+Anh+anhbnhe180420%40fpt.edu.vn', '2026-05-26 12:15:24+07', 'add_user.txt', 'HE180420'),
  ('khoakvhe180786@fpt.edu.vn', 'Kiều Văn Khoa', NULL, 'https://ui-avatars.com/api/?name=Ki%E1%BB%81u+V%C4%83n+Khoa&background=random&color=fff&size=96&bold=true&format=png&seed=Ki%E1%BB%81u+V%C4%83n+Khoa+khoakvhe180786%40fpt.edu.vn', '2026-06-05 16:46:48+07', 'add_user.txt', 'HE180786'),
  ('ductmhe180875@fpt.edu.vn', 'Từ Minh Đức', NULL, 'https://ui-avatars.com/api/?name=T%E1%BB%AB+Minh+%C4%90%E1%BB%A9c&background=random&color=fff&size=96&bold=true&format=png&seed=T%E1%BB%AB+Minh+%C4%90%E1%BB%A9c+ductmhe180875%40fpt.edu.vn', '2026-06-24 21:00:49+07', 'add_user.txt', 'HE180875'),
  ('kyvkhe182094@fpt.edu.vn', 'Vũ Kim Kỳ', NULL, 'https://ui-avatars.com/api/?name=V%C5%A9+Kim+K%E1%BB%B3&background=random&color=fff&size=96&bold=true&format=png&seed=V%C5%A9+Kim+K%E1%BB%B3+kyvkhe182094%40fpt.edu.vn', '2026-05-21 17:44:21+07', 'add_user.txt', 'HE182094'),
  ('dangtmhe182287@fpt.edu.vn', 'Trương Minh Đăng', NULL, 'https://ui-avatars.com/api/?name=Tr%C6%B0%C6%A1ng+Minh+%C4%90%C4%83ng&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%C6%B0%C6%A1ng+Minh+%C4%90%C4%83ng+dangtmhe182287%40fpt.edu.vn', '2026-05-17 10:19:07+07', 'add_user.txt', 'HE182287'),
  ('tupahe182346@fpt.edu.vn', 'Phan Anh Tú', NULL, 'https://ui-avatars.com/api/?name=Phan+Anh+T%C3%BA&background=random&color=fff&size=96&bold=true&format=png&seed=Phan+Anh+T%C3%BA+tupahe182346%40fpt.edu.vn', '2026-05-22 06:59:25+07', 'add_user.txt', 'HE182346'),
  ('dungtthe187051@fpt.edu.vn', 'Trần Trung Dũng', NULL, 'https://ui-avatars.com/api/?name=Tr%E1%BA%A7n+Trung+D%C5%A9ng&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BA%A7n+Trung+D%C5%A9ng+dungtthe187051%40fpt.edu.vn', '2026-06-15 07:27:05+07', 'add_user.txt', 'HE187051'),
  ('dinhnvhe187279@fpt.edu.vn', 'Nguyễn Văn Dinh', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+V%C4%83n+Dinh&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+V%C4%83n+Dinh+dinhnvhe187279%40fpt.edu.vn', '2026-05-18 13:03:16+07', 'add_user.txt', 'HE187279'),
  ('buiminhh2010@gmail.com', 'Bùi Quang Minh', NULL, 'https://ui-avatars.com/api/?name=B%C3%B9i+Quang+Minh&background=random&color=fff&size=96&bold=true&format=png&seed=B%C3%B9i+Quang+Minh+buiminhh2010%40gmail.com', '2026-06-12 16:17:59+07', 'tournament_csv + tournament_csv', NULL),
  ('nadung09022007@gmail.com', 'Nguyễn anh dũng', '0888585939', 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+anh+d%C5%A9ng&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+anh+d%C5%A9ng+nadung09022007%40gmail.com', '2026-06-13 21:31:42+07', 'tournament_csv', NULL),
  ('hoang151207@gmail.com', 'Nguyễn Lê Hoàng', '0866667685', 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+L%C3%AA+Ho%C3%A0ng&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+L%C3%AA+Ho%C3%A0ng+hoang151207%40gmail.com', '2026-06-15 02:12:59+07', 'tournament_csv', NULL),
  ('taikhoancuavietn@gmail.com', 'Nguyễn Quốc Việt', '0866765173', 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Qu%E1%BB%91c+Vi%E1%BB%87t&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Qu%E1%BB%91c+Vi%E1%BB%87t+taikhoancuavietn%40gmail.com', '2026-06-16 18:52:04+07', 'tournament_csv', NULL),
  ('anhtuan19091999@gmail.com', 'Tạ Anh Tuấn', '0966508897', 'https://ui-avatars.com/api/?name=T%E1%BA%A1+Anh+Tu%E1%BA%A5n&background=random&color=fff&size=96&bold=true&format=png&seed=T%E1%BA%A1+Anh+Tu%E1%BA%A5n+anhtuan19091999%40gmail.com', '2026-06-18 09:15:11+07', 'tournament_csv', NULL),
  ('tuanlyminh34@gmail.com', 'Lý Minh Tuấn', '0336417588', 'https://ui-avatars.com/api/?name=L%C3%BD+Minh+Tu%E1%BA%A5n&background=random&color=fff&size=96&bold=true&format=png&seed=L%C3%BD+Minh+Tu%E1%BA%A5n+tuanlyminh34%40gmail.com', '2026-06-18 10:18:48+07', 'tournament_csv', NULL),
  ('thehuy8425gg@gmail.com', 'Phương Thế Huy', '0336559070', 'https://ui-avatars.com/api/?name=Ph%C6%B0%C6%A1ng+Th%E1%BA%BF+Huy&background=random&color=fff&size=96&bold=true&format=png&seed=Ph%C6%B0%C6%A1ng+Th%E1%BA%BF+Huy+thehuy8425gg%40gmail.com', '2026-06-18 12:16:58+07', 'tournament_csv', NULL),
  ('nguyenquybao270707@gmail.com', 'Nguyễn Quý Bảo', '0345212156', 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Qu%C3%BD+B%E1%BA%A3o&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Qu%C3%BD+B%E1%BA%A3o+nguyenquybao270707%40gmail.com', '2026-06-18 18:42:30+07', 'tournament_csv', NULL),
  ('canhkieu51@gmail.com', 'KIỀU VĂN CẢNH', '0379986029', 'https://ui-avatars.com/api/?name=KI%E1%BB%80U+V%C4%82N+C%E1%BA%A2NH&background=random&color=fff&size=96&bold=true&format=png&seed=KI%E1%BB%80U+V%C4%82N+C%E1%BA%A2NH+canhkieu51%40gmail.com', '2026-06-18 19:20:57+07', 'tournament_csv', NULL),
  ('tranhieubentrung@gmail.com', 'Trần Minh Hiếu', '0342629624', 'https://ui-avatars.com/api/?name=Tr%E1%BA%A7n+Minh+Hi%E1%BA%BFu&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BA%A7n+Minh+Hi%E1%BA%BFu+tranhieubentrung%40gmail.com', '2026-06-20 21:59:42+07', 'tournament_csv', NULL),
  ('tranhiensqlq1976@gmail.com', 'Lê Đình Hiếu', '0339904966', 'https://ui-avatars.com/api/?name=L%C3%AA+%C4%90%C3%ACnh+Hi%E1%BA%BFu&background=random&color=fff&size=96&bold=true&format=png&seed=L%C3%AA+%C4%90%C3%ACnh+Hi%E1%BA%BFu+tranhiensqlq1976%40gmail.com', '2026-06-20 22:21:18+07', 'tournament_csv', NULL),
  ('ngohieu29122004@gmail.com', 'Ngô Minh Hiếu', '0355351321', 'https://ui-avatars.com/api/?name=Ng%C3%B4+Minh+Hi%E1%BA%BFu&background=random&color=fff&size=96&bold=true&format=png&seed=Ng%C3%B4+Minh+Hi%E1%BA%BFu+ngohieu29122004%40gmail.com', '2026-06-21 11:04:18+07', 'tournament_csv', NULL),
  ('hieuuuuu2606@gmail.com', 'Trần Trung Hiếu', '0365512005', 'https://ui-avatars.com/api/?name=Tr%E1%BA%A7n+Trung+Hi%E1%BA%BFu&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BA%A7n+Trung+Hi%E1%BA%BFu+hieuuuuu2606%40gmail.com', '2026-06-21 13:17:17+07', 'tournament_csv', NULL),
  ('hunghaohan03@gmail.com', 'Vũ Phùng Hưng', '0386838624', 'https://ui-avatars.com/api/?name=V%C5%A9+Ph%C3%B9ng+H%C6%B0ng&background=random&color=fff&size=96&bold=true&format=png&seed=V%C5%A9+Ph%C3%B9ng+H%C6%B0ng+hunghaohan03%40gmail.com', '2026-06-21 23:41:16+07', 'tournament_csv', NULL),
  ('nguyenduynam121006@gmail.com', 'Nguyễn Duy Nam', '0914290371', 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Duy+Nam&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Duy+Nam+nguyenduynam121006%40gmail.com', '2026-06-22 12:56:42+07', 'tournament_csv', NULL),
  ('namakemono1504@gmail.com', 'Trần Nam Phong', '0395348599', 'https://ui-avatars.com/api/?name=Tr%E1%BA%A7n+Nam+Phong&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BA%A7n+Nam+Phong+namakemono1504%40gmail.com', '2026-06-22 13:32:46+07', 'tournament_csv', NULL),
  ('doanhquan190104@gmail.com', 'Đỗ Anh Quân', '0982039700', 'https://ui-avatars.com/api/?name=%C4%90%E1%BB%97+Anh+Qu%C3%A2n&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90%E1%BB%97+Anh+Qu%C3%A2n+doanhquan190104%40gmail.com', '2026-06-23 12:57:27+07', 'tournament_csv', NULL),
  ('nguyenanhminh07012004@gmail.com', 'nguyễn anh minh', '0912333702', 'https://ui-avatars.com/api/?name=nguy%E1%BB%85n+anh+minh&background=random&color=fff&size=96&bold=true&format=png&seed=nguy%E1%BB%85n+anh+minh+nguyenanhminh07012004%40gmail.com', '2026-06-23 13:57:17+07', 'tournament_csv', NULL),
  ('hs186432nguyenminhhoang@gmail.com', 'Thái Hoàng', '0912727371', 'https://ui-avatars.com/api/?name=Th%C3%A1i+Ho%C3%A0ng&background=random&color=fff&size=96&bold=true&format=png&seed=Th%C3%A1i+Ho%C3%A0ng+hs186432nguyenminhhoang%40gmail.com', '2026-06-23 23:40:40+07', 'tournament_csv', NULL),
  ('thanhvttb2004@gmail.com', 'Phạm Huy Hoàng', '0348254030', 'https://ui-avatars.com/api/?name=Ph%E1%BA%A1m+Huy+Ho%C3%A0ng&background=random&color=fff&size=96&bold=true&format=png&seed=Ph%E1%BA%A1m+Huy+Ho%C3%A0ng+thanhvttb2004%40gmail.com', '2026-06-24 15:38:54+07', 'tournament_csv', NULL),
  ('tranhieuhuy0409@gmail.com', 'Huy', '0866040903', 'https://ui-avatars.com/api/?name=Huy&background=random&color=fff&size=96&bold=true&format=png&seed=Huy+tranhieuhuy0409%40gmail.com', '2026-06-24 15:50:51+07', 'tournament_csv', NULL),
  ('duc1711xh@gmail.com', 'Đinh Minh Đức', NULL, 'https://ui-avatars.com/api/?name=%C4%90inh+Minh+%C4%90%E1%BB%A9c&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90inh+Minh+%C4%90%E1%BB%A9c+duc1711xh%40gmail.com', '2026-06-25 10:20:11+07', 'tournament_csv', NULL),
  ('nguyenvantiep@gmail.com', 'Nguyễn Thái Minh', NULL, 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+Th%C3%A1i+Minh&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+Th%C3%A1i+Minh+nguyenvantiep%40gmail.com', '2026-06-25 10:34:01+07', 'tournament_csv', NULL),
  ('namdvhs180853@fpt.edu.vn', 'Dương Văn Nam', '0392123210', 'https://ui-avatars.com/api/?name=D%C6%B0%C6%A1ng+V%C4%83n+Nam&background=random&color=fff&size=96&bold=true&format=png&seed=D%C6%B0%C6%A1ng+V%C4%83n+Nam+namdvhs180853%40fpt.edu.vn', '2026-06-15 21:50:47+07', 'tournament_csv', NULL),
  ('kaitokidtokyanh@gmail.com', 'Hoàng Kỳ Anh', '0924998555', 'https://ui-avatars.com/api/?name=Ho%C3%A0ng+K%E1%BB%B3+Anh&background=random&color=fff&size=96&bold=true&format=png&seed=Ho%C3%A0ng+K%E1%BB%B3+Anh+kaitokidtokyanh%40gmail.com', '2026-06-16 18:03:48+07', 'tournament_csv', NULL),
  ('trinhphankien299@gmail.com', 'Trịnh Phan Kien', '0975750556', 'https://ui-avatars.com/api/?name=Tr%E1%BB%8Bnh+Phan+Kien&background=random&color=fff&size=96&bold=true&format=png&seed=Tr%E1%BB%8Bnh+Phan+Kien+trinhphankien299%40gmail.com', '2026-06-20 12:34:07+07', 'tournament_csv', NULL),
  ('hdamquang045@gmail.com', 'Đàm quang huy', '0989422480', 'https://ui-avatars.com/api/?name=%C4%90%C3%A0m+quang+huy&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90%C3%A0m+quang+huy+hdamquang045%40gmail.com', '2026-06-23 12:10:59+07', 'tournament_csv', NULL),
  ('mvi298258@gmail.com', 'anh tú', '0866562332', 'https://ui-avatars.com/api/?name=anh+t%C3%BA&background=random&color=fff&size=96&bold=true&format=png&seed=anh+t%C3%BA+mvi298258%40gmail.com', '2026-06-23 23:38:08+07', 'tournament_csv', NULL),
  ('tranglinh280506@gmail.com', 'Văn Tiệp', '0967280506', 'https://ui-avatars.com/api/?name=V%C4%83n+Ti%E1%BB%87p&background=random&color=fff&size=96&bold=true&format=png&seed=V%C4%83n+Ti%E1%BB%87p+tranglinh280506%40gmail.com', '2026-06-24 09:34:02+07', 'tournament_csv', NULL),
  ('dieubuihoang2003@gmail.com', 'Tuấn Soobin', '0966508897', 'https://ui-avatars.com/api/?name=Tu%E1%BA%A5n+Soobin&background=random&color=fff&size=96&bold=true&format=png&seed=Tu%E1%BA%A5n+Soobin+dieubuihoang2003%40gmail.com', '2026-06-24 09:48:20+07', 'tournament_csv', NULL),
  ('pqanh13dz@gmail.com', 'Nguyễn Hồng Phúc', '0976701155', 'https://ui-avatars.com/api/?name=Nguy%E1%BB%85n+H%E1%BB%93ng+Ph%C3%BAc&background=random&color=fff&size=96&bold=true&format=png&seed=Nguy%E1%BB%85n+H%E1%BB%93ng+Ph%C3%BAc+pqanh13dz%40gmail.com', '2026-06-24 22:45:04+07', 'tournament_csv', NULL),
  ('linh.nhm2004@gmail.com', 'Đinh Minh Đức', '0388953535', 'https://ui-avatars.com/api/?name=%C4%90inh+Minh+%C4%90%E1%BB%A9c&background=random&color=fff&size=96&bold=true&format=png&seed=%C4%90inh+Minh+%C4%90%E1%BB%A9c+linh.nhm2004%40gmail.com', '2026-06-24 23:13:13+07', 'tournament_csv', NULL)
ON CONFLICT (email) DO UPDATE SET
  full_name = EXCLUDED.full_name,
  phone = COALESCE(tmp_netup_user_import.phone, EXCLUDED.phone),
  avatar_url = EXCLUDED.avatar_url,
  created_at = LEAST(tmp_netup_user_import.created_at, EXCLUDED.created_at),
  source = tmp_netup_user_import.source || ' + ' || EXCLUDED.source,
  student_code = COALESCE(NULLIF(tmp_netup_user_import.student_code, ''), EXCLUDED.student_code);

-- Remove previously generated synthetic users if they are not attached to business records.
DELETE FROM public.users u
WHERE u.email::text LIKE 'tournament+%@netup.local'
  AND NOT EXISTS (SELECT 1 FROM public.bookings b WHERE b.player_user_id = u.id)
  AND NOT EXISTS (SELECT 1 FROM public.match_participants mp WHERE mp.player_user_id = u.id)
  AND NOT EXISTS (SELECT 1 FROM public.match_feedback mf WHERE mf.from_user_id = u.id OR mf.to_user_id = u.id)
  AND NOT EXISTS (SELECT 1 FROM public.chat_room_members crm WHERE crm.user_id = u.id)
  AND NOT EXISTS (SELECT 1 FROM public.chat_messages cm WHERE cm.sender_user_id = u.id)
  AND NOT EXISTS (SELECT 1 FROM public.court_complexes cc WHERE cc.owner_user_id = u.id)
  AND NOT EXISTS (SELECT 1 FROM public.courts c WHERE c.owner_user_id = u.id)
  AND NOT EXISTS (SELECT 1 FROM public.sessions s WHERE s.created_by_user_id = u.id)
  AND NOT EXISTS (SELECT 1 FROM public.tournament_registrations tr WHERE tr.player_user_id = u.id);

-- Upsert user profiles.
INSERT INTO public.users (email, full_name, avatar_url, phone, is_active, created_at, updated_at)
SELECT
  email::citext,
  full_name,
  avatar_url,
  NULLIF(phone, ''),
  true,
  created_at,
  GREATEST(created_at, now() - interval '3 days')
FROM tmp_netup_user_import
ON CONFLICT (email) DO UPDATE SET
  full_name = EXCLUDED.full_name,
  avatar_url = COALESCE(NULLIF(public.users.avatar_url, ''), EXCLUDED.avatar_url),
  phone = COALESCE(NULLIF(public.users.phone, ''), EXCLUDED.phone),
  is_active = true,
  created_at = LEAST(public.users.created_at, EXCLUDED.created_at),
  updated_at = now();

-- Grant player role for imported users.
INSERT INTO public.user_role_assignments (user_id, role, granted_at, reason)
SELECT u.id, 'player'::public.user_role, i.created_at, 'bulk import: add_user + tournament csv'
FROM public.users u
JOIN tmp_netup_user_import i ON i.email::citext = u.email
ON CONFLICT DO NOTHING;

-- Create default Elo profile so rating-dependent screens have a row ready.
INSERT INTO public.elo_ratings (
  player_user_id,
  elo_value,
  visible_skill_tier,
  matches_played,
  wins,
  losses,
  draws
)
SELECT
  u.id,
  1000,
  'Beginner'::public.skill_tier,
  0,
  0,
  0,
  0
FROM public.users u
JOIN tmp_netup_user_import i ON i.email::citext = u.email
ON CONFLICT (player_user_id) DO NOTHING;

-- Quick verification result after import.
SELECT
  count(*) AS imported_user_count,
  count(*) FILTER (WHERE i.source LIKE '%add_user%') AS from_add_user_or_matched,
  count(*) FILTER (WHERE i.source LIKE '%tournament_csv%') AS from_tournament_csv_or_matched,
  count(*) FILTER (WHERE u.phone IS NOT NULL) AS users_with_phone,
  count(*) FILTER (WHERE u.avatar_url IS NOT NULL) AS users_with_avatar
FROM tmp_netup_user_import i
JOIN public.users u ON u.email = i.email::citext;

COMMIT;
