-- Import NetUp users from:
-- 1. add_user.txt
-- 2. ĐĂNG KÝ THAM GIA GIẢI ĐẤU NETUP MASTER CHAMPIONSHIP 2026 (Câu trả lời) - Câu trả lời biểu mẫu 1.csv
--
-- Generated by Codex on 2026-06-30.
-- Raw student rows: 123; unique student users: 106.
-- Raw CSV participant rows: 66; unique CSV participant rows: 65.
-- CSV participants matched to student users: 2; CSV-only users added: 63.
-- Total unique users in this import: 169.
--
-- This SQL is idempotent: running it again updates existing users by email,
-- keeps existing phone when present, and does not duplicate player roles or Elo rows.

BEGIN;

CREATE TEMP TABLE tmp_netup_user_import (
  email text PRIMARY KEY,
  full_name text NOT NULL,
  phone text,
  source text NOT NULL,
  student_code text
) ON COMMIT DROP;

INSERT INTO tmp_netup_user_import (email, full_name, phone, source, student_code)
VALUES
  ('kientthe180644@fpt.edu.vn', 'Trần Trung Kiên', NULL, 'add_user.txt', 'HE180644'),
  ('quynhntha180024@fpt.edu.vn', 'Nguyễn Thị Quỳnh', NULL, 'add_user.txt', 'HA180024'),
  ('lannthha180045@fpt.edu.vn', 'Nguyễn Thị Hương Lan', NULL, 'add_user.txt', 'HA180045'),
  ('ngannttha194048@fpt.edu.vn', 'Nguyễn Thị Thảo Ngân', NULL, 'add_user.txt', 'HA194048'),
  ('manhvhhe151064@fpt.edu.vn', 'Vũ Hữu Mạnh', NULL, 'add_user.txt', 'HE151064'),
  ('namldhe163161@fpt.edu.vn', 'Lê Duy Nam', NULL, 'add_user.txt', 'HE163161'),
  ('minhnnhe171269@fpt.edu.vn', 'Nguyễn Nhật Minh', NULL, 'add_user.txt', 'HE171269'),
  ('vanntthe172704@fpt.edu.vn', 'Nguyễn Thị Thảo Vân', NULL, 'add_user.txt', 'HE172704'),
  ('quanlnmhe173240@fpt.edu.vn', 'Lê Nam Minh Quân', NULL, 'add_user.txt', 'HE173240'),
  ('dieunhhe173250@fpt.edu.vn', 'Nguyễn Huyền Diệu', NULL, 'add_user.txt', 'HE173250'),
  ('longnvhe176277@fpt.edu.vn', 'Nguyễn Văn Long', NULL, 'add_user.txt', 'HE176277'),
  ('thangnhhe176506@fpt.edu.vn', 'Nguyễn Hữu Thắng', NULL, 'add_user.txt', 'HE176506'),
  ('minhlqhe176560@fpt.edu.vn', 'Lê Quang Minh', NULL, 'add_user.txt', 'HE176560'),
  ('anhdhlhe180028@fpt.edu.vn', 'Đặng Huyền Linh Anh', NULL, 'add_user.txt', 'HE180028'),
  ('minhlahe180101@fpt.edu.vn', 'Lương Anh Minh', NULL, 'add_user.txt', 'HE180101'),
  ('hungnqhe180166@fpt.edu.vn', 'Nguyễn Quang Hùng', NULL, 'add_user.txt', 'HE180166'),
  ('ducnvhe180297@fpt.edu.vn', 'Ngô Văn Đức', NULL, 'add_user.txt', 'HE180297'),
  ('minhpvhe180323@fpt.edu.vn', 'Phạm Văn Minh', NULL, 'add_user.txt', 'HE180323'),
  ('hoangtmhe180734@fpt.edu.vn', 'Trương Minh Hoàng', NULL, 'add_user.txt', 'HE180734'),
  ('luonghdhe180950@fpt.edu.vn', 'Hoàng Đức Lương', NULL, 'add_user.txt', 'HE180950'),
  ('khoitthe180953@fpt.edu.vn', 'Trần Trọng Khôi', NULL, 'add_user.txt', 'HE180953'),
  ('namnthe180997@fpt.edu.vn', 'Nguyễn Thế Nam', NULL, 'add_user.txt', 'HE180997'),
  ('sondhthe181119@fpt.edu.vn', 'Dương Hữu Thái Sơn', NULL, 'add_user.txt', 'HE181119'),
  ('sonnphe181147@fpt.edu.vn', 'Nguyễn Phi Sơn', NULL, 'add_user.txt', 'HE181147'),
  ('duynthe181173@fpt.edu.vn', 'Nguyễn Tiến Duy', '0929933883', 'add_user.txt + tournament_csv', 'HE181173'),
  ('thanhndhe181562@fpt.edu.vn', 'Nguyễn Doanh Thành', NULL, 'add_user.txt', 'HE181562'),
  ('tungcthe181657@fpt.edu.vn', 'Chu Thanh Tùng', NULL, 'add_user.txt', 'HE181657'),
  ('thinhnphe181767@fpt.edu.vn', 'Nguyễn Phú Thịnh', NULL, 'add_user.txt', 'HE181767'),
  ('thanhnche181769@fpt.edu.vn', 'Nguyễn Công Thành', NULL, 'add_user.txt', 'HE181769'),
  ('hieudthe182175@fpt.edu.vn', 'Đoàn Trung Hiếu', NULL, 'add_user.txt', 'HE182175'),
  ('dungdahe182194@fpt.edu.vn', 'Dương Anh Dũng', NULL, 'add_user.txt', 'HE182194'),
  ('tuyenpvhe182212@fpt.edu.vn', 'Phạm Văn Tuyền', NULL, 'add_user.txt', 'HE182212'),
  ('haucvhe182292@fpt.edu.vn', 'Cao Văn Hậu', NULL, 'add_user.txt', 'HE182292'),
  ('anhdvthe186053@fpt.edu.vn', 'Đặng Văn Thái Anh', NULL, 'add_user.txt', 'HE186053'),
  ('ducnhhe186325@fpt.edu.vn', 'Nông Hoàng Đức', NULL, 'add_user.txt', 'HE186325'),
  ('hunghmhe186414@fpt.edu.vn', 'Hoàng Mạnh Hùng', NULL, 'add_user.txt', 'HE186414'),
  ('huongntmhe186558@fpt.edu.vn', 'Nguyễn Thị Mai Hương', NULL, 'add_user.txt', 'HE186558'),
  ('anhnlhe186577@fpt.edu.vn', 'Nguyễn Lan Anh', NULL, 'add_user.txt', 'HE186577'),
  ('hieunhhe186643@fpt.edu.vn', 'Nguyễn Hoàng Hiếu', NULL, 'add_user.txt', 'HE186643'),
  ('thangnlqhe186665@fpt.edu.vn', 'Nguyễn Lê Quang Thắng', NULL, 'add_user.txt', 'HE186665'),
  ('myntthe186699@fpt.edu.vn', 'Nguyễn Thị Trà My', NULL, 'add_user.txt', 'HE186699'),
  ('khanhddhe186712@fpt.edu.vn', 'Đới Duy Khánh', NULL, 'add_user.txt', 'HE186712'),
  ('lucvdhe186800@fpt.edu.vn', 'Vũ Đức Lực', NULL, 'add_user.txt', 'HE186800'),
  ('vinhnthe186877@fpt.edu.vn', 'Nguyễn Thế Vinh', NULL, 'add_user.txt', 'HE186877'),
  ('mihhhe186879@fpt.edu.vn', 'Hà Hoàng Mi', NULL, 'add_user.txt', 'HE186879'),
  ('thaolphe187244@fpt.edu.vn', 'Lê Phương Thảo', NULL, 'add_user.txt', 'HE187244'),
  ('anhntlhe187298@fpt.edu.vn', 'Nguyễn Trần Lan Anh', NULL, 'add_user.txt', 'HE187298'),
  ('duongnthe187318@fpt.edu.vn', 'Nguyễn Thanh Dương', NULL, 'add_user.txt', 'HE187318'),
  ('longnthe187346@fpt.edu.vn', 'Ngô Trung Long', NULL, 'add_user.txt', 'HE187346'),
  ('namtnnha189000@fpt.edu.vn', 'Trần Nguyễn Ngọc Nam', NULL, 'add_user.txt', 'HA189000'),
  ('thaitqhe171880@fpt.edu.vn', 'Trần Quốc Thái', NULL, 'add_user.txt', 'HE171880'),
  ('sondnhe180400@fpt.edu.vn', 'Đinh Ngọc Sơn', NULL, 'add_user.txt', 'HE180400'),
  ('longnhhe181326@fpt.edu.vn', 'Nguyễn Hoàng Long', NULL, 'add_user.txt', 'HE181326'),
  ('daidqhe181335@fpt.edu.vn', 'Đỗ Quang Đại', NULL, 'add_user.txt', 'HE181335'),
  ('datdthe181500@fpt.edu.vn', 'Đỗ Tiến Đạt', NULL, 'add_user.txt', 'HE181500'),
  ('trongpdhe181640@fpt.edu.vn', 'Phạm Đức Trọng', NULL, 'add_user.txt', 'HE181640'),
  ('vietnqhe181751@fpt.edu.vn', 'Nguyễn Quốc Việt', '0866765173', 'add_user.txt + tournament_csv', 'HE181751'),
  ('haoqtthe181812@fpt.edu.vn', 'Quách Thị Thu Hảo', NULL, 'add_user.txt', 'HE181812'),
  ('khangthe182024@fpt.edu.vn', 'Tạ Khang', NULL, 'add_user.txt', 'HE182024'),
  ('datnnhe182327@fpt.edu.vn', 'Nguyễn Ngọc Đạt', NULL, 'add_user.txt', 'HE182327'),
  ('canndhe182335@fpt.edu.vn', 'Nhữ Đình Cần', NULL, 'add_user.txt', 'HE182335'),
  ('anhnphe186085@fpt.edu.vn', 'Nguyễn Phan Anh', NULL, 'add_user.txt', 'HE186085'),
  ('khangndhe186523@fpt.edu.vn', 'Nguyễn Đăng Khang', NULL, 'add_user.txt', 'HE186523'),
  ('namnxhe186666@fpt.edu.vn', 'Ngô Xuân Nam', NULL, 'add_user.txt', 'HE186666'),
  ('tammshe186670@fpt.edu.vn', 'Mai Sỹ Tâm', NULL, 'add_user.txt', 'HE186670'),
  ('thangtxhe187306@fpt.edu.vn', 'Trịnh Xuân Thắng', NULL, 'add_user.txt', 'HE187306'),
  ('yendhhs180066@fpt.edu.vn', 'Đỗ Hải Yến', NULL, 'add_user.txt', 'HS180066'),
  ('chinths180312@fpt.edu.vn', 'Nguyễn Thuỳ Chi', NULL, 'add_user.txt', 'HS180312'),
  ('thohdhs180426@fpt.edu.vn', 'Hoàng Đức Thọ', NULL, 'add_user.txt', 'HS180426'),
  ('nhitnhs180593@fpt.edu.vn', 'Trần Ngọc Nhi', NULL, 'add_user.txt', 'HS180593'),
  ('trangntths180642@fpt.edu.vn', 'Nguyễn Thị Thuỳ Trang', NULL, 'add_user.txt', 'HS180642'),
  ('linhptths186049@fpt.edu.vn', 'Phạm Thị Thùy Linh', NULL, 'add_user.txt', 'HS186049'),
  ('lyntnhs186212@fpt.edu.vn', 'Nguyễn Thị Ngọc Ly', NULL, 'add_user.txt', 'HS186212'),
  ('hoangnmhs186432@fpt.edu.vn', 'Nguyễn Minh Hoàng', NULL, 'add_user.txt', 'HS186432'),
  ('minhndhs186449@fpt.edu.vn', 'Nguyễn Đắc Minh', NULL, 'add_user.txt', 'HS186449'),
  ('trangdths186456@fpt.edu.vn', 'Đỗ Thu Trang', NULL, 'add_user.txt', 'HS186456'),
  ('quangnvhs186464@fpt.edu.vn', 'Nguyễn Văn Quang', NULL, 'add_user.txt', 'HS186464'),
  ('khanhtqhs189004@fpt.edu.vn', 'Trịnh Quốc Khánh', NULL, 'add_user.txt', 'HS189004'),
  ('duclahe160057@fpt.edu.vn', 'Lưu Anh Đức', NULL, 'add_user.txt', 'HE160057'),
  ('hieunthe176207@fpt.edu.vn', 'Nguyễn Trung Hiếu', NULL, 'add_user.txt', 'HE176207'),
  ('annthe180486@fpt.edu.vn', 'Nguyễn Trường An', NULL, 'add_user.txt', 'HE180486'),
  ('lamkdhe180931@fpt.edu.vn', 'Kiều Đức Lâm', NULL, 'add_user.txt', 'HE180931'),
  ('khoapvhe181066@fpt.edu.vn', 'Phạm Văn Khoa', NULL, 'add_user.txt', 'HE181066'),
  ('tuanpqhe181869@fpt.edu.vn', 'Phạm Quốc Tuấn', NULL, 'add_user.txt', 'HE181869'),
  ('duclmhe182150@fpt.edu.vn', 'Lê Minh Đức', NULL, 'add_user.txt', 'HE182150'),
  ('linhdpnhe182172@fpt.edu.vn', 'Đỗ Phạm Ngọc Linh', NULL, 'add_user.txt', 'HE182172'),
  ('phuongnmhe186354@fpt.edu.vn', 'Nguyễn Minh Phương', NULL, 'add_user.txt', 'HE186354'),
  ('tanvmhe186791@fpt.edu.vn', 'Vũ Minh Tân', NULL, 'add_user.txt', 'HE186791'),
  ('cuongndhe186815@fpt.edu.vn', 'Nguyễn Đức Cường', NULL, 'add_user.txt', 'HE186815'),
  ('dungtmhe186884@fpt.edu.vn', 'Trần Minh Dũng', NULL, 'add_user.txt', 'HE186884'),
  ('thangnche186902@fpt.edu.vn', 'Nguyễn Chiến Thắng', NULL, 'add_user.txt', 'HE186902'),
  ('khaidqhe186918@fpt.edu.vn', 'Đặng Quang Khải', NULL, 'add_user.txt', 'HE186918'),
  ('trieulvhe187167@fpt.edu.vn', 'Lê Văn Triệu', NULL, 'add_user.txt', 'HE187167'),
  ('hieulxhe187201@fpt.edu.vn', 'Lê Xuân Hiếu', NULL, 'add_user.txt', 'HE187201'),
  ('trunglqhe170149@fpt.edu.vn', 'Lương Quang Trung', NULL, 'add_user.txt', 'HE170149'),
  ('vietvdqhe170516@fpt.edu.vn', 'Vũ Đoàn Quốc Việt', NULL, 'add_user.txt', 'HE170516'),
  ('ngoctmhe171577@fpt.edu.vn', 'Trần Minh Ngọc', NULL, 'add_user.txt', 'HE171577'),
  ('binhdthe176177@fpt.edu.vn', 'Đặng Tấn Bình', NULL, 'add_user.txt', 'HE176177'),
  ('anhbnhe180420@fpt.edu.vn', 'Bùi Ngọc Anh', NULL, 'add_user.txt', 'HE180420'),
  ('khoakvhe180786@fpt.edu.vn', 'Kiều Văn Khoa', NULL, 'add_user.txt', 'HE180786'),
  ('ductmhe180875@fpt.edu.vn', 'Từ Minh Đức', NULL, 'add_user.txt', 'HE180875'),
  ('kyvkhe182094@fpt.edu.vn', 'Vũ Kim Kỳ', NULL, 'add_user.txt', 'HE182094'),
  ('dangtmhe182287@fpt.edu.vn', 'Trương Minh Đăng', NULL, 'add_user.txt', 'HE182287'),
  ('tupahe182346@fpt.edu.vn', 'Phan Anh Tú', NULL, 'add_user.txt', 'HE182346'),
  ('dungtthe187051@fpt.edu.vn', 'Trần Trung Dũng', NULL, 'add_user.txt', 'HE187051'),
  ('dinhnvhe187279@fpt.edu.vn', 'Nguyễn Văn Dinh', NULL, 'add_user.txt', 'HE187279'),
  ('buiminhh2010@gmail.com', 'Bùi Quang Minh', NULL, 'tournament_csv', NULL),
  ('tournament+nguyen.minh.tien.row2@netup.local', 'Nguyễn Minh Tiến', NULL, 'tournament_csv', NULL),
  ('nadung09022007@gmail.com', 'Nguyễn anh dũng', '0888585939', 'tournament_csv', NULL),
  ('tournament+tran.vinh.hien.6586@netup.local', 'Trần vinh hiển', '0982956586', 'tournament_csv', NULL),
  ('hoang151207@gmail.com', 'Nguyễn Lê Hoàng', '0866667685', 'tournament_csv', NULL),
  ('tournament+le.toan.5607@netup.local', 'Lê Toản', '0384135607', 'tournament_csv', NULL),
  ('tournament+tran.bao.phuc.3205@netup.local', 'Trần Bảo Phúc', '0395903205', 'tournament_csv', NULL),
  ('anhtuan19091999@gmail.com', 'Tạ Anh Tuấn', '0966508897', 'tournament_csv', NULL),
  ('tournament+ho.manh.dung.8897@netup.local', 'Hồ Mạnh Dũng', '0966508897', 'tournament_csv', NULL),
  ('tuanlyminh34@gmail.com', 'Lý Minh Tuấn', '0336417588', 'tournament_csv', NULL),
  ('tournament+can.nhat.tan.6455@netup.local', 'Cấn Nhật Tân', '0362346455', 'tournament_csv', NULL),
  ('thehuy8425gg@gmail.com', 'Phương Thế Huy', '0336559070', 'tournament_csv', NULL),
  ('tournament+chu.anh.thai.7319@netup.local', 'Chu Anh Thái', '0965207319', 'tournament_csv', NULL),
  ('nguyenquybao270707@gmail.com', 'Nguyễn Quý Bảo', '0345212156', 'tournament_csv', NULL),
  ('tournament+pham.duc.duy.3776@netup.local', 'Phạm Đức Duy', '0379383776', 'tournament_csv', NULL),
  ('canhkieu51@gmail.com', 'KIỀU VĂN CẢNH', '0379986029', 'tournament_csv', NULL),
  ('tournament+luu.cong.tuan.hanh.4586@netup.local', 'LƯU CÔNG TUẤN HẠNH', '035654586', 'tournament_csv', NULL),
  ('tranhieubentrung@gmail.com', 'Trần Minh Hiếu', '0342629624', 'tournament_csv', NULL),
  ('tournament+nguyen.gia.dang.row11@netup.local', 'Nguyễn Gia Đăng', NULL, 'tournament_csv', NULL),
  ('tranhiensqlq1976@gmail.com', 'Lê Đình Hiếu', '0339904966', 'tournament_csv', NULL),
  ('tournament+duong.duc.anh.0988@netup.local', 'Dương đức anh', '0373270988', 'tournament_csv', NULL),
  ('ngohieu29122004@gmail.com', 'Ngô Minh Hiếu', '0355351321', 'tournament_csv', NULL),
  ('tournament+cao.quang.anh.1321@netup.local', 'Cao quang anh', '0355351321', 'tournament_csv', NULL),
  ('hieuuuuu2606@gmail.com', 'Trần Trung Hiếu', '0365512005', 'tournament_csv', NULL),
  ('tournament+phan.nhat.duy.row14@netup.local', 'Phan Nhất Duy', NULL, 'tournament_csv', NULL),
  ('hunghaohan03@gmail.com', 'Vũ Phùng Hưng', '0386838624', 'tournament_csv', NULL),
  ('tournament+luu.tuan.kiet.0279@netup.local', 'Lưu Tuấn Kiệt', '0399580279', 'tournament_csv', NULL),
  ('nguyenduynam121006@gmail.com', 'Nguyễn Duy Nam', '0914290371', 'tournament_csv', NULL),
  ('tournament+pham.phuong.dong.0371@netup.local', 'Phạm Phương Đông', '0914290371', 'tournament_csv', NULL),
  ('namakemono1504@gmail.com', 'Trần Nam Phong', '0395348599', 'tournament_csv', NULL),
  ('tournament+tran.manh.quang.3118@netup.local', 'Trần Mạnh Quang', '0969473118', 'tournament_csv', NULL),
  ('doanhquan190104@gmail.com', 'Đỗ Anh Quân', '0982039700', 'tournament_csv', NULL),
  ('tournament+kieu.dang.vuong.5704@netup.local', 'Kiều Đăng Vượng', '0869185704', 'tournament_csv', NULL),
  ('nguyenanhminh07012004@gmail.com', 'nguyễn anh minh', '0912333702', 'tournament_csv', NULL),
  ('hs186432nguyenminhhoang@gmail.com', 'Thái Hoàng', '0912727371', 'tournament_csv', NULL),
  ('tournament+luu.manh.dung.5151@netup.local', 'Lưu Mạnh Dũng', '0912095151', 'tournament_csv', NULL),
  ('thanhvttb2004@gmail.com', 'Phạm Huy Hoàng', '0348254030', 'tournament_csv', NULL),
  ('tournament+pham.duc.thanh.8349@netup.local', 'Phạm Đức Thành', '0961948349', 'tournament_csv', NULL),
  ('tranhieuhuy0409@gmail.com', 'Huy', '0866040903', 'tournament_csv', NULL),
  ('tournament+tung.2946@netup.local', 'Tùng', '0886312946', 'tournament_csv', NULL),
  ('duc1711xh@gmail.com', 'Đinh Minh Đức', NULL, 'tournament_csv', NULL),
  ('tournament+nguyen.dang.hoang.hai.row23@netup.local', 'Nguyễn Đăng Hoàng Hải', NULL, 'tournament_csv', NULL),
  ('nguyenvantiep@gmail.com', 'Nguyễn Thái Minh', NULL, 'tournament_csv', NULL),
  ('tournament+nguyen.van.tiep.row24@netup.local', 'Nguyễn Văn Tiệp', NULL, 'tournament_csv', NULL),
  ('tournament+doan.vu.trang.row25@netup.local', 'Đoàn Vũ Trang', NULL, 'tournament_csv', NULL),
  ('namdvhs180853@fpt.edu.vn', 'Dương Văn Nam', '0392123210', 'tournament_csv', NULL),
  ('tournament+nguyen.tuong.vy.0315@netup.local', 'Nguyễn Tường Vy', '0363680315', 'tournament_csv', NULL),
  ('kaitokidtokyanh@gmail.com', 'Hoàng Kỳ Anh', '0924998555', 'tournament_csv', NULL),
  ('tournament+nguyen.minh.thuy.5298@netup.local', 'Nguyễn Minh Thuý', '0988705298', 'tournament_csv', NULL),
  ('trinhphankien299@gmail.com', 'Trịnh Phan Kien', '0975750556', 'tournament_csv', NULL),
  ('tournament+tran.thi.huyen.3590@netup.local', 'Trần Thị Huyền', '0976363590', 'tournament_csv', NULL),
  ('hdamquang045@gmail.com', 'Đàm quang huy', '0989422480', 'tournament_csv', NULL),
  ('tournament+nguyen.hai.yen.5008@netup.local', 'Nguyễn hải yến', '0334095008', 'tournament_csv', NULL),
  ('mvi298258@gmail.com', 'anh tú', '0866562332', 'tournament_csv', NULL),
  ('tournament+mai.anh.1650@netup.local', 'mai anh', '0862301650', 'tournament_csv', NULL),
  ('tranglinh280506@gmail.com', 'Văn Tiệp', '0967280506', 'tournament_csv', NULL),
  ('tournament+trang.linh.0506@netup.local', 'Trang Linh', '0967280506', 'tournament_csv', NULL),
  ('dieubuihoang2003@gmail.com', 'Tuấn Soobin', '0966508897', 'tournament_csv', NULL),
  ('tournament+bui.hoang.dieu.0903@netup.local', 'Bùi Hoàng Diệu', '0912180903', 'tournament_csv', NULL),
  ('pqanh13dz@gmail.com', 'Nguyễn Hồng Phúc', '0976701155', 'tournament_csv', NULL),
  ('tournament+phung.kim.thanh.1155@netup.local', 'Phùng Kim Thanh', '0976701155', 'tournament_csv', NULL),
  ('linh.nhm2004@gmail.com', 'Đinh Minh Đức', '0388953535', 'tournament_csv', NULL),
  ('tournament+nguyen.hoang.mai.linh.3535@netup.local', 'Nguyễn Hoàng Mai Linh', '0388953535', 'tournament_csv', NULL)
ON CONFLICT (email) DO UPDATE SET
  full_name = EXCLUDED.full_name,
  phone = COALESCE(tmp_netup_user_import.phone, EXCLUDED.phone),
  source = tmp_netup_user_import.source || ' + ' || EXCLUDED.source,
  student_code = COALESCE(NULLIF(tmp_netup_user_import.student_code, ''), EXCLUDED.student_code);

-- Upsert user profiles.
INSERT INTO public.users (email, full_name, phone, is_active)
SELECT
  email::citext,
  full_name,
  NULLIF(phone, ''),
  true
FROM tmp_netup_user_import
ON CONFLICT (email) DO UPDATE SET
  full_name = EXCLUDED.full_name,
  phone = COALESCE(NULLIF(public.users.phone, ''), EXCLUDED.phone),
  is_active = true,
  updated_at = now();

-- Grant player role for imported users.
INSERT INTO public.user_role_assignments (user_id, role, reason)
SELECT u.id, 'player'::public.user_role, 'bulk import: add_user + tournament csv'
FROM public.users u
JOIN tmp_netup_user_import i ON i.email::citext = u.email
ON CONFLICT DO NOTHING;

-- Create default Elo profile so rating-dependent screens have a row ready.
INSERT INTO public.elo_ratings (
  player_user_id,
  elo_value,
  visible_skill_tier,
  matches_played,
  wins,
  losses,
  draws
)
SELECT
  u.id,
  1000,
  'Beginner'::public.skill_tier,
  0,
  0,
  0,
  0
FROM public.users u
JOIN tmp_netup_user_import i ON i.email::citext = u.email
ON CONFLICT (player_user_id) DO NOTHING;

-- Quick verification result after import.
SELECT
  count(*) AS imported_user_count,
  count(*) FILTER (WHERE i.source LIKE '%add_user%') AS from_add_user_or_matched,
  count(*) FILTER (WHERE i.source LIKE '%tournament_csv%') AS from_tournament_csv_or_matched,
  count(*) FILTER (WHERE u.phone IS NOT NULL) AS users_with_phone
FROM tmp_netup_user_import i
JOIN public.users u ON u.email = i.email::citext;

COMMIT;
